name: ViewCube Documentation

on:
  push:
    branches:
      - main  # Change to your main branch if it's different
  pull_request:
    branches:
      - main  # Run on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # Add other dependencies as needed

      - name: Build documentation
        run: |
          cd docs  # Change to your docs directory if needed
          sphinx-build -b html . _build/html  # Adjust paths as necessary

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html  # Path to your built HTML files
          publish_branch: gh-pages  # Branch to publish to
